#ifndef INCLUDED_OS_CONFIG_H
#define INCLUDED_OS_CONFIG_H

#ifndef RTOS_KERNEL_TLSF_POOL_SIZE
#define RTOS_KERNEL_TLSF_POOL_SIZE (1024*10)
#endif

#define OS_TICKS_PER_SECOND 100

#ifndef OS_PRINTF_USE_DEFAULT_IMPLEMENTATION
#define OS_PRINTF_USE_DEFAULT_IMPLEMENTATION 1
#endif /*OS_PRINTF_USE_DEFAULT_IMPLEMENTATION*/

#ifndef OS_ENABLE
#define OS_ENABLE 1
#endif

#endif /*INCLUDED_OS_CONFIG_H*/
