#ifndef INCLUDED_CPU_DEFINITIONS_H
#define INCLUDED_CPU_DEFINITIONS_H

#ifndef __FPU_PRESENT
#define __FPU_PRESENT 1
#endif

#ifndef CPU_HARDFAULT_ENABLE
#define CPU_HARDFAULT_ENABLE 0
#endif

#endif /*INCLUDED_CPU_DEFINITIONS_H*/
