#ifndef INCLUDED_CPU_DEFINITIONS_H
#define INCLUDED_CPU_DEFINITIONS_H

#ifndef __FPU_PRESENT
#define __FPU_PRESENT 1
#endif

#ifndef __FPU_USED
#define __FPU_USED 1
#endif

#ifndef CPU_HARDFAULT_ENABLE
#define CPU_HARDFAULT_ENABLE 1
#endif

#ifndef CPU_STACK_INIT_WITH_PRIVILEGE
#define CPU_STACK_INIT_WITH_PRIVILEGE 0
#endif

#ifndef CPU_HARDFAULT_ENABLE
#define CPU_HARDFAULT_ENABLE 2
#endif


#ifndef CPU_HARDFAULT_ENABLE
#define CPU_HARDFAULT_ENABLE 2
#endif

#endif /*INCLUDED_CPU_DEFINITIONS_H*/
